Added option for linear lr schedule
AI4SCR/conditional-monge pull request #12
Opened 2024-08-26 12:33 UTC by DriessenA

Adding the possibility to use a linear LR schedular with kwargs

2024-08-26 22:21 UTC, jannisborn requested changes

2024-08-26 22:21 UTC, jannisborn commented on cmonge/trainers/conditional_monge_trainer.py
> +                **self.config.lr_scheduler.kwags,
typo alarm: `kwargs` instead of `kwags` ?

2024-08-26 22:21 UTC, jannisborn commented on cmonge/trainers/conditional_monge_trainer.py
> +        if self.config.lr_scheduler.name.lower() == "cosine":
you could use a`.get()..` here to ensure the default behavior is the cosine scheduler and guarantee that old configs will still run

2024-08-27 05:38 UTC, DriessenA commented on cmonge/trainers/conditional_monge_trainer.py
> +                **self.config.lr_scheduler.kwags,
Ah yeah whoops, typo

2024-08-27 13:41 UTC, jannisborn approved these changes

2024-08-27 13:42 UTC, merged