MongeMapTrainer checkpoint saving and loading
AI4SCR/conditional-monge pull request #18
Opened 2024-10-24 15:32 UTC by DriessenA

Added checkpoint saving and loading to the Monge Map trainer. I used this for the CAR exp but I think it is in general quite usefull

2024-10-25 07:52 UTC, jannisborn requested changes
That's definitely a good idea. Some changes required to robustify code, we could do the same for the conditional trainers

2024-10-25 07:52 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +                """Please provide a checkpoint save path
mention in error that model checkpoint was not saved

2024-10-25 07:52 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +        out_class = cls(
wrap whole method in try/except block and add a meaningful error msg

2024-10-25 07:52 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +        if path is None and config is None:
return here otherwise downstream code will fail

2024-10-25 08:42 UTC, DriessenA reviewed
Okay, I think all changes have been implemented

2024-10-25 11:11 UTC, jannisborn requested changes

2024-10-25 11:11 UTC, jannisborn commented on cmonge/trainers/conditional_monge_trainer.py
> +                        through the model config"""
single quotes and one line

2024-10-25 11:11 UTC, jannisborn commented on cmonge/trainers/conditional_monge_trainer.py
> +        except:
dont use bare except

2024-10-25 11:11 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +    ) -> None:
adapt type annotation

2024-10-25 11:11 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +            return
this return is useless

2024-10-25 11:50 UTC, DriessenA commented on cmonge/trainers/conditional_monge_trainer.py
> +        except:
replaced with `except Exception`

2024-10-25 11:50 UTC, DriessenA commented on cmonge/trainers/ot_trainer.py
> +    ) -> None:
Return type now `Union[MongeMapTrainer, None]`

2024-10-26 13:21 UTC, jannisborn commented on cmonge/trainers/conditional_monge_trainer.py
> +            )
```suggestion
            logger.error("Please provide a checkpoint save path either directly or through the config, checkpoint was NOT saved.")
```

2024-10-26 13:22 UTC, jannisborn commented on cmonge/trainers/conditional_monge_trainer.py
> +            return
```suggestion
```

2024-10-26 13:22 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +            return
```suggestion
```

2024-10-26 13:24 UTC, jannisborn requested changes

2024-10-26 13:24 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +        if path is None and config is None:
you are still not returning

2024-10-26 13:24 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +                """Please provide a checkpoint save path
again single quotes/line are enough

2024-10-28 09:44 UTC, DriessenA commented
So this code is now good to go?

I just saw your comments from the weekend, weird that you didn't see the changes... I'm sure I changed those things.

2024-10-28 10:25 UTC, closed without merging