Added sklearn logging and checkpointing
AI4SCR/conditional-monge pull request #2
Opened 2024-04-22 07:59 UTC by DriessenA

Adding sklearn logging and checkpointing. Additionally, some minor additions to work with the CAR data

2024-04-23 07:03 UTC, jannisborn requested changes
great work overall, both in code style but also in ensuring backwards compatibility. Just some small remarks then we can merge

2024-04-23 07:03 UTC, jannisborn commented on cmonge/checkpointing/__init__.py
Let's remove this empty folder

2024-04-23 07:03 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +        log_mean_metrics(self.metrics, mlflow_logging=self.mlflow_logging)
The `mlflow_logging` attribute is not defined in this base class. Either define it in constructor (you can add it as a boolean with default False for full backwards compatability) or move this line out of the base class to the child classes

2024-04-23 07:03 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +                valid_freq=100,  # mlflow logging not implemented here
I would add a `logger.warning("MLFlow not implemented for ..."` here

2024-04-24 13:41 UTC, DriessenA commented on cmonge/checkpointing/__init__.py
The folder isn't empty and the init is needed?

2024-04-24 13:50 UTC, jannisborn commented on cmonge/checkpointing/__init__.py
Maybe you have unpushed changes but I dont see any code in this folder (just an empty init and another empty `.py`), hence my suggestion to delete

2024-04-24 13:52 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +        self, jobid: int, logger_path: Path, mlflow_logging: bool = False
Now you're passing the variable but you're not registering as attribute in the constructor

2024-04-24 13:54 UTC, jannisborn commented on cmonge/trainers/ot_trainer.py
> +        # Potentially overwrite AbstractTrainer attribute
This is not necessary, just move the attribute to the constructor of this class and then pass it down to the parent class via `super().__init__()`

2024-04-26 20:49 UTC, jannisborn approved these changes

2024-04-26 20:50 UTC, merged